// <auto-generated />
using BulkyBooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyBooks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241223042641_addValuesDbCat")]
    partial class addValuesDbCat : addValuesDbCatBase
    {
    }
}
